"""add created_at and updated_at to leave_requests

Revision ID: 89bfd60c1009
Revises: 9d71293d2ed1
Create Date: 2025-04-16 21:47:03.858983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bfd60c1009'
down_revision: Union[str, None] = '9d71293d2ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('leave_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'updated_at')
    op.drop_column('leave_requests', 'created_at')
    # ### end Alembic commands ###
