"""initial

Revision ID: 8d50c0ddb723
Revises: eed316ac0d2a
Create Date: 2025-05-01 13:43:00.111039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d50c0ddb723'
down_revision: Union[str, None] = 'eed316ac0d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('tornado_approval', sa.Boolean(), nullable=True))
    op.add_column('leave_requests', sa.Column('zitel_approval', sa.Boolean(), nullable=True))
    op.drop_column('leave_requests', 'team_lead_approved')
    op.drop_column('leave_requests', 'zitel_approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('zitel_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('team_lead_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('leave_requests', 'zitel_approval')
    op.drop_column('leave_requests', 'tornado_approval')
    # ### end Alembic commands ###
